"""initial schema

Revision ID: e69b899cc6b1
Revises: 
Create Date: 2026-04-22 17:09:44.371527

"""
from alembic import op
import sqlalchemy as sa



# revision identifiers, used by Alembic.
revision = 'e69b899cc6b1'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('admission_checklist_steps',
    sa.Column('step_order', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=180), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_admission_checklist_steps_step_order', 'admission_checklist_steps', ['step_order'], unique=False)
    op.create_table('approval_workflow_templates',
    sa.Column('code', sa.String(length=80), nullable=False),
    sa.Column('name', sa.String(length=180), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('request_kind', sa.Enum('ANY', 'ADMISSION', 'DISMISSAL', name='approvalrequestkindenum', native_enum=False, length=20), nullable=False),
    sa.Column('origin_group', sa.Enum('COORDINATOR_SUPERVISOR', 'MANAGER', 'ANY', name='approvalorigingroupenum', native_enum=False, length=30), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_index('ix_approval_workflow_templates_is_active', 'approval_workflow_templates', ['is_active'], unique=False)
    op.create_index('ix_approval_workflow_templates_origin_group', 'approval_workflow_templates', ['origin_group'], unique=False)
    op.create_index('ix_approval_workflow_templates_request_kind', 'approval_workflow_templates', ['request_kind'], unique=False)
    op.create_table('departments',
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('total_people', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code', name='uq_departments_code'),
    sa.UniqueConstraint('name', name='uq_departments_name')
    )
    op.create_index('ix_departments_is_active', 'departments', ['is_active'], unique=False)
    op.create_table('dismissal_checklist_steps',
    sa.Column('step_order', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=180), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_dismissal_checklist_steps_step_order', 'dismissal_checklist_steps', ['step_order'], unique=False)
    op.create_table('job_titles',
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code', name='uq_job_titles_code'),
    sa.UniqueConstraint('name', name='uq_job_titles_name')
    )
    op.create_index('ix_job_titles_is_active', 'job_titles', ['is_active'], unique=False)
    op.create_table('surveys',
    sa.Column('code', sa.String(length=60), nullable=False),
    sa.Column('name', sa.String(length=180), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('category', sa.String(length=120), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code', name='uq_surveys_code')
    )
    op.create_table('users',
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=150), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('role', sa.Enum('RH_ADMIN', 'RH_ANALISTA', 'RH_PESQUISAS', 'GESTOR', 'DIRETOR_RAVI', 'COLABORADOR', name='roleenum', native_enum=False, length=30), nullable=False),
    sa.Column('auth_source', sa.Enum('LOCAL', 'LDAP', name='authenticationsourceenum', native_enum=False, length=20), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_index('ix_users_is_active', 'users', ['is_active'], unique=False)
    op.create_index('ix_users_role', 'users', ['role'], unique=False)
    op.create_table('admission_requests',
    sa.Column('status', sa.Enum('PENDING', 'APPROVED', 'FINALIZED', 'REJECTED', name='admissionrequeststatusenum', native_enum=False, length=20), nullable=False),
    sa.Column('request_type', sa.Enum('GROWTH', 'REPLACEMENT', name='admissionrequesttypeenum', native_enum=False, length=20), nullable=False),
    sa.Column('posicao_vaga', sa.Enum('PUBLIC_ADMINISTRATIVE', 'PUBLIC_OPERATIONAL', 'PUBLIC_LEADERSHIP', name='admissionpositionenum', native_enum=False, length=30), nullable=False),
    sa.Column('is_confidential', sa.Boolean(), nullable=False),
    sa.Column('recruiter_user_id', sa.Integer(), nullable=True),
    sa.Column('cargo', sa.String(length=150), nullable=False),
    sa.Column('setor', sa.String(length=150), nullable=False),
    sa.Column('recruitment_scope', sa.Enum('INTERNAL', 'EXTERNAL', 'MIXED', name='recruitmentscopeenum', native_enum=False, length=20), nullable=False),
    sa.Column('quantity_people', sa.Integer(), nullable=False),
    sa.Column('turno', sa.String(length=80), nullable=False),
    sa.Column('contract_regime', sa.Enum('TEMPORARY', 'EFFECTIVE', 'INTERN', 'APPRENTICE', 'CLT', 'PJ', name='contractregimeenum', native_enum=False, length=20), nullable=False),
    sa.Column('substituted_employee_name', sa.String(length=150), nullable=True),
    sa.Column('justification', sa.Text(), nullable=True),
    sa.Column('manager_reminder', sa.Text(), nullable=True),
    sa.Column('submitted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('finalized_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('checklist_completed_steps', sa.Integer(), nullable=False),
    sa.Column('created_by_user_id', sa.Integer(), nullable=False),
    sa.Column('approval_workflow_template_id', sa.Integer(), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['approval_workflow_template_id'], ['approval_workflow_templates.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['recruiter_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_admission_requests_created_by_user_id', 'admission_requests', ['created_by_user_id'], unique=False)
    op.create_index('ix_admission_requests_status', 'admission_requests', ['status'], unique=False)
    op.create_index('ix_admission_requests_submitted_at', 'admission_requests', ['submitted_at'], unique=False)
    op.create_index('ix_admission_requests_type', 'admission_requests', ['request_type'], unique=False)
    op.create_table('approval_workflow_steps',
    sa.Column('workflow_template_id', sa.Integer(), nullable=False),
    sa.Column('step_order', sa.Integer(), nullable=False),
    sa.Column('approver_role', sa.Enum('MANAGER', 'DIRECTOR_RAVI', 'RH_MANAGER', name='approvalroleenum', native_enum=False, length=30), nullable=False),
    sa.Column('approver_label', sa.String(length=150), nullable=False),
    sa.Column('is_required', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['workflow_template_id'], ['approval_workflow_templates.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_approval_workflow_steps_step_order', 'approval_workflow_steps', ['step_order'], unique=False)
    op.create_index('ix_approval_workflow_steps_workflow_template_id', 'approval_workflow_steps', ['workflow_template_id'], unique=False)
    op.create_table('audit_logs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('actor_user_id', sa.Integer(), nullable=True),
    sa.Column('action', sa.Enum('CREATE', 'UPDATE', 'DELETE', 'LOGIN', 'PUBLISH', 'SUBMIT', name='auditactionenum', native_enum=False, length=20), nullable=False),
    sa.Column('entity_name', sa.String(length=120), nullable=False),
    sa.Column('entity_id', sa.String(length=50), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('details_json', sa.Text(), nullable=True),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['actor_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_audit_logs_actor_user_id', 'audit_logs', ['actor_user_id'], unique=False)
    op.create_index('ix_audit_logs_created_at', 'audit_logs', ['created_at'], unique=False)
    op.create_index('ix_audit_logs_entity_name', 'audit_logs', ['entity_name'], unique=False)
    op.create_table('dismissal_requests',
    sa.Column('status', sa.Enum('PENDING', 'UNDER_REVIEW', 'APPROVED', 'REJECTED', 'CANCELED', name='dismissalrequeststatusenum', native_enum=False, length=20), nullable=False),
    sa.Column('dismissal_type', sa.Enum('JUST_CAUSE', 'RESIGNATION', 'WITHOUT_JUST_CAUSE', 'TERM_CONTRACT', 'CONSENSUAL', name='dismissalrequesttypeenum', native_enum=False, length=30), nullable=False),
    sa.Column('employee_name', sa.String(length=150), nullable=False),
    sa.Column('cargo', sa.String(length=150), nullable=False),
    sa.Column('departamento', sa.String(length=150), nullable=False),
    sa.Column('has_replacement', sa.Boolean(), nullable=False),
    sa.Column('can_be_rehired', sa.Boolean(), nullable=False),
    sa.Column('rehire_justification', sa.Text(), nullable=True),
    sa.Column('recruiter_user_id', sa.Integer(), nullable=True),
    sa.Column('post_approval_rejection_reason', sa.Text(), nullable=True),
    sa.Column('post_approval_rejected_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('estimated_termination_date', sa.Date(), nullable=False),
    sa.Column('contract_regime', sa.Enum('TEMPORARY', 'EFFECTIVE', 'INTERN', 'APPRENTICE', 'CLT', 'PJ', name='contractregimeenum', native_enum=False, length=20), nullable=False),
    sa.Column('manager_reminder', sa.Text(), nullable=True),
    sa.Column('created_by_user_id', sa.Integer(), nullable=False),
    sa.Column('submitted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('checklist_completed_steps', sa.Integer(), nullable=False),
    sa.Column('approval_workflow_template_id', sa.Integer(), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['approval_workflow_template_id'], ['approval_workflow_templates.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['recruiter_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_dismissal_requests_created_by_user_id', 'dismissal_requests', ['created_by_user_id'], unique=False)
    op.create_index('ix_dismissal_requests_estimated_termination_date', 'dismissal_requests', ['estimated_termination_date'], unique=False)
    op.create_index('ix_dismissal_requests_status', 'dismissal_requests', ['status'], unique=False)
    op.create_index('ix_dismissal_requests_type', 'dismissal_requests', ['dismissal_type'], unique=False)
    op.create_table('survey_dimensions',
    sa.Column('survey_id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=60), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('display_order', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['survey_id'], ['surveys.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('survey_id', 'code', name='uq_survey_dimensions_survey_code'),
    sa.UniqueConstraint('survey_id', 'name', name='uq_survey_dimensions_survey_name')
    )
    op.create_index('ix_survey_dimensions_display_order', 'survey_dimensions', ['display_order'], unique=False)
    op.create_index('ix_survey_dimensions_survey_id', 'survey_dimensions', ['survey_id'], unique=False)
    op.create_table('survey_versions',
    sa.Column('survey_id', sa.Integer(), nullable=False),
    sa.Column('version_number', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=180), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('DRAFT', 'PUBLISHED', 'ARCHIVED', name='surveyversionstatusenum', native_enum=False, length=20), nullable=False),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['survey_id'], ['surveys.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('survey_id', 'version_number', name='uq_survey_versions_survey_version')
    )
    op.create_index('ix_survey_versions_status', 'survey_versions', ['status'], unique=False)
    op.create_index('ix_survey_versions_survey_id', 'survey_versions', ['survey_id'], unique=False)
    op.create_table('user_module_access',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('module', sa.Enum('DASHBOARD', 'ADMISSION', 'DISMISSAL', 'SURVEYS', 'APPROVALS', 'ACCESS_CONTROL', name='accessmoduleenum', native_enum=False, length=40), nullable=False),
    sa.Column('access_level', sa.Enum('READ', 'MANAGE', name='accesslevelenum', native_enum=False, length=20), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('granted_by_user_id', sa.Integer(), nullable=True),
    sa.Column('granted_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('note', sa.String(length=1000), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['granted_by_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'module', name='uq_user_module_access_user_module')
    )
    op.create_index('ix_user_module_access_is_active', 'user_module_access', ['is_active'], unique=False)
    op.create_index('ix_user_module_access_module', 'user_module_access', ['module'], unique=False)
    op.create_index('ix_user_module_access_user_id', 'user_module_access', ['user_id'], unique=False)
    op.create_table('admission_request_approvals',
    sa.Column('admission_request_id', sa.Integer(), nullable=False),
    sa.Column('workflow_step_id', sa.Integer(), nullable=True),
    sa.Column('step_order', sa.Integer(), nullable=False),
    sa.Column('approver_role', sa.Enum('MANAGER', 'DIRECTOR_RAVI', 'RH_MANAGER', name='approvalroleenum', native_enum=False, length=30), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'APPROVED', 'REJECTED', 'SKIPPED', name='approvalstepstatusenum', native_enum=False, length=20), nullable=False),
    sa.Column('assigned_to_user_id', sa.Integer(), nullable=True),
    sa.Column('decided_by_user_id', sa.Integer(), nullable=True),
    sa.Column('decided_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('comments', sa.Text(), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['admission_request_id'], ['admission_requests.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['assigned_to_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['decided_by_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['workflow_step_id'], ['approval_workflow_steps.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_admission_request_approvals_admission_request_id', 'admission_request_approvals', ['admission_request_id'], unique=False)
    op.create_index('ix_admission_request_approvals_status', 'admission_request_approvals', ['status'], unique=False)
    op.create_index('ix_admission_request_approvals_step_order', 'admission_request_approvals', ['step_order'], unique=False)
    op.create_table('campaigns',
    sa.Column('survey_version_id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=60), nullable=False),
    sa.Column('name', sa.String(length=180), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('start_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('end_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.Enum('DRAFT', 'ACTIVE', 'CLOSED', name='campaignstatusenum', native_enum=False, length=20), nullable=False),
    sa.Column('is_anonymous', sa.Boolean(), nullable=False),
    sa.Column('allows_draft', sa.Boolean(), nullable=False),
    sa.Column('created_by_user_id', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.CheckConstraint('start_at < end_at', name='ck_campaigns_period'),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['survey_version_id'], ['survey_versions.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code', name='uq_campaigns_code')
    )
    op.create_index('ix_campaigns_period', 'campaigns', ['start_at', 'end_at'], unique=False)
    op.create_index('ix_campaigns_status', 'campaigns', ['status'], unique=False)
    op.create_index('ix_campaigns_survey_version_id', 'campaigns', ['survey_version_id'], unique=False)
    op.create_table('dismissal_request_approvals',
    sa.Column('dismissal_request_id', sa.Integer(), nullable=False),
    sa.Column('workflow_step_id', sa.Integer(), nullable=True),
    sa.Column('step_order', sa.Integer(), nullable=False),
    sa.Column('approver_role', sa.Enum('MANAGER', 'DIRECTOR_RAVI', 'RH_MANAGER', name='approvalroleenum', native_enum=False, length=30), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'APPROVED', 'REJECTED', 'SKIPPED', name='approvalstepstatusenum', native_enum=False, length=20), nullable=False),
    sa.Column('assigned_to_user_id', sa.Integer(), nullable=True),
    sa.Column('decided_by_user_id', sa.Integer(), nullable=True),
    sa.Column('decided_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('comments', sa.Text(), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['assigned_to_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['decided_by_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['dismissal_request_id'], ['dismissal_requests.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['workflow_step_id'], ['approval_workflow_steps.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_dismissal_request_approvals_dismissal_request_id', 'dismissal_request_approvals', ['dismissal_request_id'], unique=False)
    op.create_index('ix_dismissal_request_approvals_status', 'dismissal_request_approvals', ['status'], unique=False)
    op.create_index('ix_dismissal_request_approvals_step_order', 'dismissal_request_approvals', ['step_order'], unique=False)
    op.create_table('employees',
    sa.Column('employee_code', sa.String(length=50), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('source_admission_request_id', sa.Integer(), nullable=True),
    sa.Column('department_id', sa.Integer(), nullable=False),
    sa.Column('job_title_id', sa.Integer(), nullable=False),
    sa.Column('manager_id', sa.Integer(), nullable=True),
    sa.Column('full_name', sa.String(length=150), nullable=False),
    sa.Column('work_email', sa.String(length=255), nullable=True),
    sa.Column('personal_email', sa.String(length=255), nullable=True),
    sa.Column('hire_date', sa.Date(), nullable=True),
    sa.Column('status', sa.Enum('ACTIVE', 'INACTIVE', 'ON_LEAVE', name='employeestatusenum', native_enum=False, length=20), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['department_id'], ['departments.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['job_title_id'], ['job_titles.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['manager_id'], ['employees.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['source_admission_request_id'], ['admission_requests.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('employee_code', name='uq_employees_employee_code'),
    sa.UniqueConstraint('user_id', name='uq_employees_user_id'),
    sa.UniqueConstraint('work_email', name='uq_employees_work_email')
    )
    op.create_index('ix_employees_department_id', 'employees', ['department_id'], unique=False)
    op.create_index('ix_employees_job_title_id', 'employees', ['job_title_id'], unique=False)
    op.create_index('ix_employees_manager_id', 'employees', ['manager_id'], unique=False)
    op.create_index('ix_employees_source_admission_request_id', 'employees', ['source_admission_request_id'], unique=False)
    op.create_index('ix_employees_status', 'employees', ['status'], unique=False)
    op.create_table('survey_questions',
    sa.Column('survey_version_id', sa.Integer(), nullable=False),
    sa.Column('dimension_id', sa.Integer(), nullable=True),
    sa.Column('code', sa.String(length=80), nullable=False),
    sa.Column('question_text', sa.Text(), nullable=False),
    sa.Column('help_text', sa.Text(), nullable=True),
    sa.Column('question_type', sa.Enum('SCALE_1_5', 'TEXT', 'SINGLE_CHOICE', name='questiontypeenum', native_enum=False, length=20), nullable=False),
    sa.Column('is_required', sa.Boolean(), nullable=False),
    sa.Column('display_order', sa.Integer(), nullable=False),
    sa.Column('scale_min', sa.Integer(), nullable=False),
    sa.Column('scale_max', sa.Integer(), nullable=False),
    sa.Column('score_weight', sa.Integer(), nullable=False),
    sa.Column('is_negative', sa.Boolean(), nullable=False),
    sa.Column('allow_comment', sa.Boolean(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.CheckConstraint('scale_min <= scale_max', name='ck_survey_questions_scale_bounds'),
    sa.ForeignKeyConstraint(['dimension_id'], ['survey_dimensions.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['survey_version_id'], ['survey_versions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('survey_version_id', 'code', name='uq_survey_questions_version_code'),
    sa.UniqueConstraint('survey_version_id', 'display_order', name='uq_survey_questions_version_order')
    )
    op.create_index('ix_survey_questions_dimension_id', 'survey_questions', ['dimension_id'], unique=False)
    op.create_index('ix_survey_questions_question_type', 'survey_questions', ['question_type'], unique=False)
    op.create_index('ix_survey_questions_survey_version_id', 'survey_questions', ['survey_version_id'], unique=False)
    op.create_table('admission_request_candidates',
    sa.Column('admission_request_id', sa.Integer(), nullable=False),
    sa.Column('employee_id', sa.Integer(), nullable=True),
    sa.Column('full_name', sa.String(length=150), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('phone_number', sa.String(length=30), nullable=True),
    sa.Column('hire_date', sa.Date(), nullable=True),
    sa.Column('is_hired', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['admission_request_id'], ['admission_requests.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_admission_request_candidates_is_hired', 'admission_request_candidates', ['is_hired'], unique=False)
    op.create_index('ix_admission_request_candidates_request_id', 'admission_request_candidates', ['admission_request_id'], unique=False)
    op.create_table('campaign_audiences',
    sa.Column('campaign_id', sa.Integer(), nullable=False),
    sa.Column('employee_id', sa.Integer(), nullable=False),
    sa.Column('employee_name_snapshot', sa.String(length=150), nullable=False),
    sa.Column('work_email_snapshot', sa.String(length=255), nullable=False),
    sa.Column('department_name_snapshot', sa.String(length=120), nullable=False),
    sa.Column('job_title_name_snapshot', sa.String(length=120), nullable=False),
    sa.Column('manager_name_snapshot', sa.String(length=150), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'STARTED', 'SUBMITTED', 'EXPIRED', name='campaignaudiencestatusenum', native_enum=False, length=20), nullable=False),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('responded_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['campaign_id'], ['campaigns.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('campaign_id', 'employee_id', name='uq_campaign_audiences_campaign_employee')
    )
    op.create_index('ix_campaign_audiences_campaign_id', 'campaign_audiences', ['campaign_id'], unique=False)
    op.create_index('ix_campaign_audiences_employee_id', 'campaign_audiences', ['employee_id'], unique=False)
    op.create_index('ix_campaign_audiences_status', 'campaign_audiences', ['status'], unique=False)
    op.create_table('question_options',
    sa.Column('question_id', sa.Integer(), nullable=False),
    sa.Column('label', sa.String(length=120), nullable=False),
    sa.Column('value', sa.String(length=60), nullable=False),
    sa.Column('score_value', sa.Integer(), nullable=True),
    sa.Column('display_order', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['question_id'], ['survey_questions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('question_id', 'display_order', name='uq_question_options_question_order'),
    sa.UniqueConstraint('question_id', 'value', name='uq_question_options_question_value')
    )
    op.create_index('ix_question_options_question_id', 'question_options', ['question_id'], unique=False)
    op.create_table('responses',
    sa.Column('campaign_id', sa.Integer(), nullable=False),
    sa.Column('campaign_audience_id', sa.Integer(), nullable=False),
    sa.Column('employee_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('DRAFT', 'SUBMITTED', name='responsestatusenum', native_enum=False, length=20), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('submitted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_anonymous_snapshot', sa.Boolean(), nullable=False),
    sa.Column('submission_ip', sa.String(length=45), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['campaign_audience_id'], ['campaign_audiences.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['campaign_id'], ['campaigns.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('campaign_audience_id', name='uq_responses_campaign_audience_id'),
    sa.UniqueConstraint('campaign_id', 'employee_id', name='uq_responses_campaign_employee')
    )
    op.create_index('ix_responses_campaign_id', 'responses', ['campaign_id'], unique=False)
    op.create_index('ix_responses_employee_id', 'responses', ['employee_id'], unique=False)
    op.create_index('ix_responses_status', 'responses', ['status'], unique=False)
    op.create_table('response_items',
    sa.Column('response_id', sa.Integer(), nullable=False),
    sa.Column('question_id', sa.Integer(), nullable=False),
    sa.Column('selected_option_id', sa.Integer(), nullable=True),
    sa.Column('numeric_answer', sa.Integer(), nullable=True),
    sa.Column('text_answer', sa.Text(), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.CheckConstraint('numeric_answer >= 1 AND numeric_answer <= 5', name='ck_response_items_numeric_answer_range'),
    sa.ForeignKeyConstraint(['question_id'], ['survey_questions.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['response_id'], ['responses.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['selected_option_id'], ['question_options.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('response_id', 'question_id', name='uq_response_items_response_question')
    )
    op.create_index('ix_response_items_question_id', 'response_items', ['question_id'], unique=False)
    op.create_index('ix_response_items_response_id', 'response_items', ['response_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_response_items_response_id', table_name='response_items')
    op.drop_index('ix_response_items_question_id', table_name='response_items')
    op.drop_table('response_items')
    op.drop_index('ix_responses_status', table_name='responses')
    op.drop_index('ix_responses_employee_id', table_name='responses')
    op.drop_index('ix_responses_campaign_id', table_name='responses')
    op.drop_table('responses')
    op.drop_index('ix_question_options_question_id', table_name='question_options')
    op.drop_table('question_options')
    op.drop_index('ix_campaign_audiences_status', table_name='campaign_audiences')
    op.drop_index('ix_campaign_audiences_employee_id', table_name='campaign_audiences')
    op.drop_index('ix_campaign_audiences_campaign_id', table_name='campaign_audiences')
    op.drop_table('campaign_audiences')
    op.drop_index('ix_admission_request_candidates_request_id', table_name='admission_request_candidates')
    op.drop_index('ix_admission_request_candidates_is_hired', table_name='admission_request_candidates')
    op.drop_table('admission_request_candidates')
    op.drop_index('ix_survey_questions_survey_version_id', table_name='survey_questions')
    op.drop_index('ix_survey_questions_question_type', table_name='survey_questions')
    op.drop_index('ix_survey_questions_dimension_id', table_name='survey_questions')
    op.drop_table('survey_questions')
    op.drop_index('ix_employees_status', table_name='employees')
    op.drop_index('ix_employees_source_admission_request_id', table_name='employees')
    op.drop_index('ix_employees_manager_id', table_name='employees')
    op.drop_index('ix_employees_job_title_id', table_name='employees')
    op.drop_index('ix_employees_department_id', table_name='employees')
    op.drop_table('employees')
    op.drop_index('ix_dismissal_request_approvals_step_order', table_name='dismissal_request_approvals')
    op.drop_index('ix_dismissal_request_approvals_status', table_name='dismissal_request_approvals')
    op.drop_index('ix_dismissal_request_approvals_dismissal_request_id', table_name='dismissal_request_approvals')
    op.drop_table('dismissal_request_approvals')
    op.drop_index('ix_campaigns_survey_version_id', table_name='campaigns')
    op.drop_index('ix_campaigns_status', table_name='campaigns')
    op.drop_index('ix_campaigns_period', table_name='campaigns')
    op.drop_table('campaigns')
    op.drop_index('ix_admission_request_approvals_step_order', table_name='admission_request_approvals')
    op.drop_index('ix_admission_request_approvals_status', table_name='admission_request_approvals')
    op.drop_index('ix_admission_request_approvals_admission_request_id', table_name='admission_request_approvals')
    op.drop_table('admission_request_approvals')
    op.drop_index('ix_user_module_access_user_id', table_name='user_module_access')
    op.drop_index('ix_user_module_access_module', table_name='user_module_access')
    op.drop_index('ix_user_module_access_is_active', table_name='user_module_access')
    op.drop_table('user_module_access')
    op.drop_index('ix_survey_versions_survey_id', table_name='survey_versions')
    op.drop_index('ix_survey_versions_status', table_name='survey_versions')
    op.drop_table('survey_versions')
    op.drop_index('ix_survey_dimensions_survey_id', table_name='survey_dimensions')
    op.drop_index('ix_survey_dimensions_display_order', table_name='survey_dimensions')
    op.drop_table('survey_dimensions')
    op.drop_index('ix_dismissal_requests_type', table_name='dismissal_requests')
    op.drop_index('ix_dismissal_requests_status', table_name='dismissal_requests')
    op.drop_index('ix_dismissal_requests_estimated_termination_date', table_name='dismissal_requests')
    op.drop_index('ix_dismissal_requests_created_by_user_id', table_name='dismissal_requests')
    op.drop_table('dismissal_requests')
    op.drop_index('ix_audit_logs_entity_name', table_name='audit_logs')
    op.drop_index('ix_audit_logs_created_at', table_name='audit_logs')
    op.drop_index('ix_audit_logs_actor_user_id', table_name='audit_logs')
    op.drop_table('audit_logs')
    op.drop_index('ix_approval_workflow_steps_workflow_template_id', table_name='approval_workflow_steps')
    op.drop_index('ix_approval_workflow_steps_step_order', table_name='approval_workflow_steps')
    op.drop_table('approval_workflow_steps')
    op.drop_index('ix_admission_requests_type', table_name='admission_requests')
    op.drop_index('ix_admission_requests_submitted_at', table_name='admission_requests')
    op.drop_index('ix_admission_requests_status', table_name='admission_requests')
    op.drop_index('ix_admission_requests_created_by_user_id', table_name='admission_requests')
    op.drop_table('admission_requests')
    op.drop_index('ix_users_role', table_name='users')
    op.drop_index('ix_users_is_active', table_name='users')
    op.drop_table('users')
    op.drop_table('surveys')
    op.drop_index('ix_job_titles_is_active', table_name='job_titles')
    op.drop_table('job_titles')
    op.drop_index('ix_dismissal_checklist_steps_step_order', table_name='dismissal_checklist_steps')
    op.drop_table('dismissal_checklist_steps')
    op.drop_index('ix_departments_is_active', table_name='departments')
    op.drop_table('departments')
    op.drop_index('ix_approval_workflow_templates_request_kind', table_name='approval_workflow_templates')
    op.drop_index('ix_approval_workflow_templates_origin_group', table_name='approval_workflow_templates')
    op.drop_index('ix_approval_workflow_templates_is_active', table_name='approval_workflow_templates')
    op.drop_table('approval_workflow_templates')
    op.drop_index('ix_admission_checklist_steps_step_order', table_name='admission_checklist_steps')
    op.drop_table('admission_checklist_steps')
    # ### end Alembic commands ###